# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & Deployment

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'docs/**'
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: '0.0.1'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        architecture: x64
    - name: Build with Maven
      run: mvn -T 2.0C clean install -DskipTests
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker Build SETL-Nifi Image
      working-directory: ./nifi-docker/dockermaven
      run: mvn -P docker clean install      

    - name: Docker Push SETL-Nifi Image to Docker Hub    
      run: docker push thaihv/setl-nifi:$VERSION

    - name: Docker Build SETL-Nifi-Registry Image
      working-directory: ./nifi-registry/nifi-registry-docker-maven/dockermaven
      run: mvn -P docker clean install      

    - name: Docker Push SETL-Nifi-Registry Image to Docker Hub    
      run: docker push thaihv/setl-nifi-registry:$VERSION

    - name: Deploy To DigitalOcean  
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{secrets.SSH_HOST}} 
        key: ${{secrets.SSH_PRIVATE_KEY}} 
        username: ${{ secrets.SSH_USERNAME }}     
        script: |  
          docker-compose -f nifi-compose.yml stop
          docker pull thaihv/setl-nifi:$VERSION
          docker-compose -f nifi-compose.yml up -d nifi
          echo 'Deployment successful to Digital Ocean' 
